
# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd_settings:
      db: null
      unlock:
        - 0x193991827e291599a262e7fa7d212ff1ae31d110
        - 0x97ca371d59bbfefdb391aa6dcbdf4455fec361f2
        - 0x3d24d77bec08549d7ea86c4e9937204c11e153f1
        - 0xcD9e6Df80169b6a2CFfDaE613fAbC3F7C3647B14
        - 0xaf379f0228ad0d46bb7b4f38f9dc9bcc1ad0360c
        - 0xc25099792e9349c7dd09759744ea681c7de2cb66
  mainnet:
    gas_price: 0
  

project_structure:
  contracts: contracts
  # contracts: contracts

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.0

compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.2.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMathUpgradeable
    - AccessControlUpgradeable
    - EnumerableSetUpgradeable
    - SafeERC20Upgradeable
    - ERC20Upgradeable