
# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd_settings:
      db: null
  mainnet:
    gas_price: 44
  live:
      gas_limit: 6000000
      gas_buffer: 1.1
      gas_price: 40000000000
      reverting_tx_gas_limit: false
      default_contract_owner: false

project_structure:
  contracts: contracts
  # contracts: contracts

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.0

compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.2.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMathUpgradeable
    - AccessControlUpgradeable
    - EnumerableSetUpgradeable
    - SafeERC20Upgradeable
    - ERC20Upgradeable